//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Nullable<double> EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Birthdate_ { get; set; }
        public string HomeState { get; set; }
        public string Gender { get; set; }
        public string WorkEMail { get; set; }
        public string PersonalEMail { get; set; }
        public int Id { get; set; }
    }
}
